[[redirects]]
  from = "/api/*"
  to = "https://api.mangadex.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/covers/*"
  to = "https://uploads.mangadex.org/covers/:splat"
  status = 200
  force = true
  headers = {Referrer-Policy = "no-referrer"}